//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket12306.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ticket12306.Resx.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [{&quot;Code&quot;:&quot;VAP&quot;,&quot;Name&quot;:&quot;北京北&quot;,&quot;ShortName&quot;:&quot;bjb&quot;,&quot;ShortName1&quot;:&quot;bjb&quot;,&quot;FullName&quot;:&quot;beijingbei&quot;},{&quot;Code&quot;:&quot;BOP&quot;,&quot;Name&quot;:&quot;北京东&quot;,&quot;ShortName&quot;:&quot;bjd&quot;,&quot;ShortName1&quot;:&quot;bjd&quot;,&quot;FullName&quot;:&quot;beijingdong&quot;},{&quot;Code&quot;:&quot;BJP&quot;,&quot;Name&quot;:&quot;北京&quot;,&quot;ShortName&quot;:&quot;bji&quot;,&quot;ShortName1&quot;:&quot;bj&quot;,&quot;FullName&quot;:&quot;beijing&quot;},{&quot;Code&quot;:&quot;VNP&quot;,&quot;Name&quot;:&quot;北京南&quot;,&quot;ShortName&quot;:&quot;bjn&quot;,&quot;ShortName1&quot;:&quot;bjn&quot;,&quot;FullName&quot;:&quot;beijingnan&quot;},{&quot;Code&quot;:&quot;BXP&quot;,&quot;Name&quot;:&quot;北京西&quot;,&quot;ShortName&quot;:&quot;bjx&quot;,&quot;ShortName1&quot;:&quot;bjx&quot;,&quot;FullName&quot;:&quot;beijingxi&quot;},{&quot;Code&quot;:&quot;IZQ&quot;,&quot;Name&quot;:&quot;广州南&quot;,&quot;ShortNa... 的本地化字符串。
        /// </summary>
        internal static string StationsJson {
            get {
                return ResourceManager.GetString("StationsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E	000000000000000111111000000111111011000110011111000110000000000110000000000110000000001110000000001111111000001111111010001100011110001100000000001100000000011100000000011100000000011111110000
        ///G	000000000000011011111000011111111100111110011110111000001110110000000100100000000000100001111110100001111110110001111111110000001111111000001111011111111110011111111100001111111000000000000000
        ///E	0000000000000000001111000000111111110001111011110001110000110011110000110011111111110011111111110011101111110011100000 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VcCode {
            get {
                return ResourceManager.GetString("VcCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R	1110000000000000001111110000000000000111000000000000001111111111011111111111111111111111100011111111100000001111111110000000001101111100000011110011111111111111001111111111111100111111000011110011111100000011000111110000000000011111100000000001111110000000
        ///W	0000000001110000000000001111110000000000111111101100000011111111111000000111111111100000011111111111100001111111111111000111110011111111011111101111111110011110110111111001111011100111111111101111101111111110111111001111111101111100011111110011110001 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VcCode0 {
            get {
                return ResourceManager.GetString("VcCode0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E	0000000000000000000000111111111100000011111111110000001111100000000000111110000011000011111000001100001111100000111000111111111111111111111111111100011111100000110000111110000000000011111111000000001111111111000000111111111111111111111111110000000000000000
        ///3	0000000000000000000000011111111100000001111111110000000111111111000000000000001100000000000000110000000000000111000000011111111101111111111111110111111111111111000000000111111100000111111111000001111111000000000111111110011100000001111111110000000111 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VcCode1 {
            get {
                return ResourceManager.GetString("VcCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R	0000000000000000111001111111111111111111011111110001111000000011111011110000111111011111001111111101111101111111001111110111111100111111001111000111111100111111011111111011111000111111101111111111100011111110011110000011110000111000000000000000000000000000
        ///8	0000000000000000011100000000010101111011000101011111010001110111011111110011011111111111111111001111010111110000111010011111000011000001111100001111100111000000111111100110000011111010011000001110111001110000111010001111000011111111111000000011111111 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VcCode2 {
            get {
                return ResourceManager.GetString("VcCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E	0000000000000000111111100011111111111111111111111111001100000000111100111100011111110011110011110011001111000111011100111100001101110011111000000111001111000111011111110000011100111111000001110001111100000000000000000000000000000001111111110000000001111111
        ///7	0000000000000000111111111111111111111111000011110000111111111000111111111111100011111111111110111111110001100111111110000000111100111110000011111111110000111110111111000011110011111111111110001111111111111000110111111111000011111111111000001111111111 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VcCode3 {
            get {
                return ResourceManager.GetString("VcCode3", resourceCulture);
            }
        }
    }
}
